version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/github.com/Tech-Design-Inc/sirius
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_SCHEMA: test
      DB_MAX_CONNECTIONS: "20"
      DB_QUERY_TIMEOUT_SECONDS: "15"

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - ./db_data:/var/lib/mysql
      - ./docker_local/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
